name: tripusfrontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  mapbox_search: any
  get_storage: 2.1.1
  file_picker: 5.3.3
  flutter: 
    sdk: flutter
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  timeago: ^3.5.0
  skeletons: ^0.0.3
  calendar_date_picker2: ^0.5.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/payment/
  uses-material-design: true

